---
version: "3.2"

services:
  build-mega-drive-examples:
    build:
      context: .
    environment:
      - MEGADRIVE_HOME=/rust-mega-drive/share
      - RUSTUP_TOOLCHAIN=m68k
      - LLVM_CONFIG=/llvm-m68k/bin/llvm-config
    volumes:
      - ./target:/target
